import { StyleSheet } from 'react-native';

export const colors = { blue: '#007AFF', ink: '#0F172A', muted: '#64748B', background: '#F2F2F7' };

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.background },
  content: { padding: 20, gap: 16, width: '100%', maxWidth: 650, alignSelf: 'center', paddingBottom: 28 },
  title: { fontSize: 34, fontWeight: '800', color: colors.ink, letterSpacing: -1 },
  subtitle: { fontSize: 15, color: colors.muted, lineHeight: 23 },
  heading: { fontSize: 20, fontWeight: '700', color: colors.ink },
  text: { fontSize: 16, color: colors.ink, lineHeight: 24 },
  card: { backgroundColor: '#FFFFFF', borderRadius: 24, padding: 20, gap: 12 },
  between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' },
  button: { backgroundColor: colors.blue, borderRadius: 16, padding: 16, minHeight: 50, alignItems: 'center' },
  secondary: { backgroundColor: '#EAF2FF' },
  danger: { backgroundColor: '#FEE2E2' },
  buttonText: { fontSize: 16, fontWeight: '700', color: '#FFFFFF', textAlign: 'center' },
  secondaryText: { color: colors.blue },
  dangerText: { color: '#B42318' },
  input: { backgroundColor: '#FFFFFF', borderRadius: 14, borderWidth: 1, borderColor: '#CBD5E1', padding: 14, minHeight: 50, fontSize: 16, color: colors.ink },
  field: { gap: 7 },
  label: { fontSize: 14, fontWeight: '600', color: colors.ink },
  error: { color: '#B42318', fontSize: 14, lineHeight: 21 },
  badge: { paddingHorizontal: 12, height: 32, borderRadius: 16, justifyContent: 'center', alignItems: 'center', backgroundColor: '#EAF2FF' },
  badgeText: { fontSize: 13, fontWeight: '600', color: '#0056B3' },
  stats: { flexDirection: 'row', gap: 12 },
  stat: { flex: 1, backgroundColor: '#FFFFFF', borderRadius: 22, padding: 16, gap: 8 },
  number: { fontSize: 32, fontWeight: '800', color: colors.blue },
  navigation: { flexDirection: 'row', marginHorizontal: 16, marginBottom: 8, padding: 6, borderRadius: 24, backgroundColor: '#FFFFFF', maxWidth: 650, alignSelf: 'center', width: '92%' },
  tab: { flex: 1, paddingVertical: 14, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  activeTab: { backgroundColor: '#EAF2FF' },
  tabText: { fontWeight: '600', fontSize: 15, color: colors.muted },
  logo: { width: 135, height: 78, alignSelf: 'flex-start' },
  option: { borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 14, padding: 14, gap: 4 },
  selected: { borderColor: colors.blue, backgroundColor: '#EAF2FF' },
  iconButton: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#FEE2E2', alignItems: 'center', justifyContent: 'center' },
  moneyRow: { flexDirection: 'row', flexWrap: 'wrap', borderTopWidth: 1, borderTopColor: '#E2E8F0', paddingTop: 12, gap: 8 },
  moneyItem: { flexGrow: 1, flexBasis: 110, gap: 4 },
  moneyLabel: { fontSize: 12, fontWeight: '600', color: colors.muted, textTransform: 'uppercase', letterSpacing: 0.4 },
  moneyValue: { fontSize: 17, fontWeight: '700', color: colors.ink },
  negative: { color: '#B42318' },
  profitPreview: { backgroundColor: '#E8F7EE', borderRadius: 16, padding: 16, gap: 5 },
  financeCard: { backgroundColor: colors.ink, borderRadius: 24, padding: 20, gap: 7 },
  financeEyebrow: { fontSize: 12, fontWeight: '700', color: '#93C5FD', letterSpacing: 1 },
  financeTotal: { fontSize: 34, fontWeight: '800', color: '#FFFFFF', letterSpacing: -1 },
  financeCaption: { fontSize: 15, color: '#CBD5E1', lineHeight: 23 },
  financeBreakdown: { flexDirection: 'row', alignItems: 'stretch', backgroundColor: '#1E293B', borderRadius: 16, padding: 14, marginTop: 8 },
  financeItem: { flex: 1, gap: 5 },
  financeLabel: { fontSize: 12, fontWeight: '600', color: '#94A3B8', textTransform: 'uppercase', letterSpacing: 0.4 },
  financeValue: { fontSize: 17, fontWeight: '700', color: '#FFFFFF' },
  financeDivider: { width: 1, backgroundColor: '#475569', marginHorizontal: 14 },
  orderTotal: { fontSize: 15, fontWeight: '700', color: colors.blue },
  loginPage: { flex: 1, backgroundColor: colors.background },
  loginContent: { flexGrow: 1, width: '100%', maxWidth: 480, alignSelf: 'center', justifyContent: 'center', padding: 24, gap: 24 },
  loginBrand: { alignItems: 'center', gap: 7 },
  loginLogo: { width: 180, height: 105 },
  loginTitle: { fontSize: 34, fontWeight: '800', color: colors.ink, letterSpacing: -1 },
  loginSubtitle: { width: '100%', fontSize: 16, color: colors.muted, lineHeight: 23, textAlign: 'center', flexShrink: 0 },
  loginCard: { backgroundColor: '#FFFFFF', borderRadius: 24, padding: 22, gap: 18 },
  loginFooter: { fontSize: 13, color: colors.muted, textAlign: 'center' },
});
